version: '3.8'

services:
  # make sure implements retry connectDB 5 times each 5s
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: user
      POSTGRES_DB: mydb
    volumes:
      # - ./pgdata:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  web:
    build: .
    # use my own custom image
    image: starwarsapi
    # make sure it starts postgres first
    depends_on:
      - db
    ports:
      - '8000:8000'

volumes:
  pgdata:
